### ISSUE TITLE
latest version not availeble in hacs installation

### ISSUE THREAD

**Issue by TheDiverM** [Danielhiversen/home_assistant_adax#15]
Hi
in hacs only versions availeble is:
v0.1.1-Beta1
v0.1.1-Beta
master

from this page there should be 0.3 availeble, but its not availe in  hacs

**Comment by Danielhiversen** [comment]
It is available here.
Sure it is not anything wrong with your hacs setup?

**Comment by TheDiverM** [comment]
was a old custom repository, from first installation. of this addon...

works rigth now
