### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by phellarv** [Danielhiversen/home_assistant_adax#18]
I'm only getting "unable to connect" when trying to add this integration via webgui.
Doublechecked userid and password.

**Comment by phellarv** [comment]
2020-10-12 17:53:14 ERROR (MainThread) [custom_components.adax.climate] Adax: Failed to login to retrieve token: 400 {"error": "invalid_grant"}

**Comment by Danielhiversen** [comment]
Are you sure you are using the correct credentials?
`account_id` is NOT your log in email for the Adax app
`password` is NOT the password you use to log in to the Adax app

**Comment by phellarv** [comment]
I found out. I needed to create a new API-password.
