### ISSUE TITLE
Improved information

### ISSUE THREAD

**Issue by perbrage** [Danielhiversen/home_assistant_adax#20]
Hi!

I’ve been trying to find heaters for some time that can be connected to HA, and now I found your integration. Good job putting this together. The main features I’m looking for would be to be able to turn the heaters on/off, set target temperature and also measure the power consumption.

From your readme.md I can’t find anwers to those questions, so I propose that you detail the features your integration is capable of in the readme.md. Perhaps together with some screenshots?

Meanwhile, perhaps you can tell me if you support the above mentioned features or plan on implementing them? I might be making a purchase of these heaters very soon.

Regards,
Per

**Comment by Danielhiversen** [comment]
Power consumption is not supported by the Adax API yet but will be later.
Turn on/off and change the set temperature is supported.
You are welcome to improve the documentation

**Comment by lhrmota** [comment]
Hi.

I just managed to install and configure this in my HA, but it was a bit of a try-and-guess process... The documentation is lacking info for people like me, not too familiar with HA,
I'd happily try to contribute to the documentation, but how should I do that? I'm not used to collaborating in other people's projects...

Best regards

**Comment by Danielhiversen** [comment]
That would be great.
You can open a pull request with your changes
