### ISSUE TITLE
HA 0.117.2 gives connecting error

### ISSUE THREAD

**Issue by DenielTorres** [Danielhiversen/home_assistant_adax#22]
Hi! 

After updating to the latest HA instance, the integration drops errors like this: 

<img width="420" alt="Screenshot 2020-11-02 at 21 15 19" src="https://user-images.githubusercontent.com/19772214/97914666-8a4fb200-1d50-11eb-8639-e916e4304082.png">

What could be the problem? 

Thanks in advance!

**Comment by Danielhiversen** [comment]
Still, getting the error?
It is an error from the Adax server and not related to you upgrading of HA

**Comment by UdoK** [comment]
Getting the same error several times a day when I want to control one of my 6 ADAX heaters from UI or through Automation. 

2020-11-03 10:23:36 ERROR (MainThread) [custom_components.adax.adax] Error connecting to Adax, response: 429 Too Many Requests

**Comment by Danielhiversen** [comment]
Hmm, maybe adax has added some rate-limiting?

**Comment by Danielhiversen** [comment]
Would be great some of you would try to increase the time here:
https://github.com/Danielhiversen/home_assistant_adax/blob/master/custom_components/adax/adax.py#L37

**Comment by UdoK** [comment]
I increased the time to 60 but same problem as before:

now - self._last_updated < datetime.timedelta(seconds=60)

Turn on the heater when Udo come home has been triggered by state of person.ich
10:43:10 AM - 48 seconds ago

2020-11-03 10:43:15 ERROR (MainThread) [custom_components.adax.adax] Error connecting to Adax, response: 429 Too Many Requests

**Comment by Danielhiversen** [comment]
Probably take some time before the rate limit is resat.

**Comment by UdoK** [comment]
Will run it with the 60s for one day and will report back the results tomorrow. 
Thanks so far!

**Comment by Danielhiversen** [comment]
Changing it to 10 minutes seems to solve it for me.

**Comment by Danielhiversen** [comment]
I changed it back to 30 seconds and it has been working fine since yesterday.
Do you still see the error from Adax?

**Comment by UdoK** [comment]
Yes, I still see the errors. 
Every change of the temperature of a heater via the UI or an Automation causes the same error again.
Problem with that is that sometimes the change will be executed, sometimes not. What is a very unstable situation.

Logger: custom_components.adax.adax
Source: custom_components/adax/adax.py:92
Integration: Adax (documentation, issues)
First occurred: 3 November 2020, 22:24:44 (16 occurrences)
Last logged: 8:49:46

Error connecting to Adax, response: 429 Too Many Requests

**Comment by Danielhiversen** [comment]
Does it seem to only happen when trying to change the set temperature? Never when fetching the heater state?
I have contacted Adax and asked if the API has some rate-limiting, but no answer yet.

**Comment by UdoK** [comment]
Errors only happen when I change the temperature or switch the heater on or off.
I don't know when the heater states will be fetched but errors will only be logged when something will be activated on one of the heaters

**Comment by caribo** [comment]
Hey @Danielhiversen , I see 429 rate limiting occurring when calling /rest/v1/content/ twice in succession from my own python script. Leaving a gap of 10 or more seconds between calls helps, but is not  guaranteed to work. I'd be interested to know what parameters Adax are using for rate limiting, especially as they do not appear to be populating the response header with any details so it is difficult to deal with programatically

**Comment by Danielhiversen** [comment]
From adax:
```

Yes, there are rules, they limit to one request a minute

And why would be so strange to ask more frequent temperature changes 🙂

```

So has started on a fix https://github.com/Danielhiversen/home_assistant_adax/pull/25
