### ISSUE TITLE
Add a Temperature Sensor

### ISSUE THREAD

**Issue by Caleroific** [Danielhiversen/home_assistant_adax#26]
I would like to add a HA Gauge Card. Would it be possible for you to add a _sensor.conservatory_ entity? Thank you.

**Comment by Caleroific** [comment]
For information I have Tado Smart Thermostatic Valves in other rooms. For HA Tado provided the following entities:

![image](https://user-images.githubusercontent.com/73845902/98441915-5af6c780-20f9-11eb-8582-365da30db530.png)

**Comment by Danielhiversen** [comment]
You can use a template sensor: https://www.home-assistant.io/integrations/template/

```
{{states.climate.adax.attributes.temperature}}
```
