### ISSUE TITLE
Delay reacting to changes

### ISSUE THREAD

**Issue by lhrmota** [Danielhiversen/home_assistant_adax#33]
Hello Daniel,

I've been using this integration for a while, and there is some issue with the reaction to changes in settings on the home assistant panel.

When I turn the heater on (or off), the UI takes usually a long time to update to the on state. The heater takes usually longer still to react to this change. The whole might take more than a minute, and it sometimes fails.

Is this common, or is it some problem with my setup?

Bye and best regards, Luís

My setup:
## System Health

version | 2020.12.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.51-v7+
arch | armv7l
timezone | Europe/Lisbon

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4979
Installed Version | 1.9.0
Stage | running
Available Repositories | 710
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 28.8 GB
disk_used | 5.7 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Instituto Português do Mar e Atmosfera (IPMA)</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | auto-gen
resources | 0

</details>

**Comment by Danielhiversen** [comment]
What do you mean by long time to update?
Seconds or minutes?

**Comment by Danielhiversen** [comment]
Have you checked your logs?
Any related errors?

**Comment by lhrmota** [comment]
Hi there.

The delay is irregular, from 10 to 30s.

There are errors in the log, as follows:

Logger: custom_components.adax.adax
Source: custom_components/adax/adax.py:133
Integration: Adax (documentation, issues)
First occurred: January 7, 2021, 4:46:55 PM (15 occurrences)
Last logged: 11:29:42 AM
Too many requests, will retry 

Best regards

**Comment by acseven** [comment]
I too have these errors occasionally, mostly when trying to set the temperature manually (I usually use a scheduler component for this). 
I guess the component tries to set the temperature instantaneously whenever we set the temperature, but given the API's behavior it might be better if the actual API request only occurred a second or two after we stopped fiddling with it (i.e. moving from 19 to 22, oh no, 21.5, wait, 21) - if this is even possible. 

Tried this just now:
![image](https://user-images.githubusercontent.com/1176371/104021199-4a74d300-51b6-11eb-8fb1-059fef7014d3.png)

**Comment by Danielhiversen** [comment]
`Too many requests, will retry` There is some (unknown) rate limiting on the Adax API. 
It never sends more than one request within 5 seconds.


So when we send a command to adax, we have to wait a while before we can ask for an updated state.
I could assume that the correct state is sat until we get an update from adax, would that be better?
The risk is if the turn-on command fails, we will show the wrong state for some seconds.

**Comment by acseven** [comment]
I find it already shows the wrong state for quite a while, given that error. The ideal behavior would be the components to have some sort of waiting status where no commands where actually possible of being submitted, but I guess that isn't possible.

That said, I guess that fiddling with the temperature could have a short delay to make sure the user has stopped fiddling with it, and that this instruction and others (heat/off) could be piped in sequence, instead of being instantaneous... 

In any case, the current implementation works, and my main issue with it is not those errors, but the actual delay in status that those errors cause in the UI for now actually showing.

**Comment by Danielhiversen** [comment]
> It never sends more than one request within 5 seconds.

**Comment by acseven** [comment]
I can't make much of an argument against that, other than the error below resulted of me fiddling with that climate component for less than 5 seconds (changing temp in a couple or so steps and pressing heat).

> 
> Tried this just now:
> ![image](https://user-images.githubusercontent.com/1176371/104021199-4a74d300-51b6-11eb-8fb1-059fef7014d3.png)

**Comment by Danielhiversen** [comment]
You can try to increase the time limit:
https://github.com/Danielhiversen/home_assistant_adax/blob/master/custom_components/adax/adax.py#L13

**Comment by lhrmota** [comment]
Hi there.

On 08/01/21 14:05, Daniel Hjelseth Høyer wrote:
>
> You can try to increase the time limit:
> https://github.com/Danielhiversen/home_assistant_adax/blob/master/custom_components/adax/adax.py#L13
>
>
I'd like to try to fiddle with this value. But I'm not sure I really 
understand what RATE_LIMIT_SECONDS means. Is this the minimum interval 
between communications with the Adax server?

Bye and thanks, Luís

**Comment by Danielhiversen** [comment]
Yes,

Example:
0s <- receive a command to send set temperature to 22, sent to adax
2s <- receive a command to send set temperature to 23, the command is delayed
5s <- delayed command with set temperature 23 is now sent

**Comment by Danielhiversen** [comment]
Would also be great if you would test this:
https://github.com/Danielhiversen/home_assistant_adax/pull/34

**Comment by lhrmota** [comment]
Hi.

Just to get this straight: what happens if several (>2) commands are 
received in a 5s time frame?

If we have, e.g,:

0s <- receive a command to send set temperature to 22
2s <- receive a command to send set temperature to 23

3s <- receive a command to send set temperature to 24
4s <- receive a command to send set temperature to 25

At 0s, the first command is sent. But after 5 s, which command is sent? 
23? Or are the intermediate commands ignored and only 25ºC is sent?

Best regards, Luís

**Comment by Danielhiversen** [comment]
25ºC is sent.
Previous commands are removed

**Comment by lhrmota** [comment]
Wouldn't it be interesting to have a similar delay for the first command?

Also, does this rate limit apply similarly to temperature and on/off 
commands?

Luís

**Comment by Danielhiversen** [comment]
The delay before the first command is 0.5seconds.
Yes, same for any requests to adax. (Also fetching the current state)
