### ISSUE TITLE
How to force refresh the integration?

### ISSUE THREAD

**Issue by zsgodor** [Danielhiversen/home_assistant_adax#35]
Dear Daniel,
I use your ADAX integration, i would like to ask, how can i refresh My thermostat card scan interval.
When i reload the integration, my thermostat card is freshing, but i don't know how set the scan interval.
The red square, my card refresh 12 minutes ago.
![Képernyőfotó 2021-02-23 - 18 31 33](https://user-images.githubusercontent.com/64435192/108883267-8698b180-7605-11eb-8d70-2ba640f11212.png)
Thank You for your help. :)

**Comment by Danielhiversen** [comment]
You can not force refresh the data from the gui
