### ISSUE TITLE
Error after upgrade new version 0.4.4 

### ISSUE THREAD

**Issue by zsgodor** [Danielhiversen/home_assistant_adax#38]
Hi Daniel,
After upgrade the new version, (0.4.4) I lost all my ADAX heater entity, and can't connect ADAX.
If I delete the integration and read, the integration added but i can't set the configuration.
Now work the old integration, 0.4.3 version, but the new is can't work for me.
Error The configuration process cannot be loaded
![Képernyőfotó 2021-04-11 - 21 38 03](https://user-images.githubusercontent.com/64435192/114319425-dbd74680-9b11-11eb-8354-4312934fc1b7.png)

Please check the new version, or please inform me, what the solution my problem.

Many Thanks Zsolt 

## System Health

version | core-2021.4.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-8-amd64
arch | x86_64
timezone | Europe/Budapest

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4629
Installed Version | 1.11.3
Stage | running
Available Repositories | 844
Installed Repositories | 10

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 36

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.9
docker_version | 19.03.11
disk_total | 113.1 GB
disk_used | 37.2 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | TasmoAdmin (0.14.1), Mosquitto broker (5.1.1), SQLite Web (2.2.2), Simple Scheduler (0.16.10), ESPHome (1.16.0), Portainer (1.1.0), File editor (5.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 2
views | 11
mode | storage

</details>

**Comment by Danielhiversen** [comment]
Any errors in the log?

**Comment by zsgodor** [comment]
Hi i update version 0.4.5, this work smoothly. :)
