### ISSUE TITLE
Variable for power consumption and heating?

### ISSUE THREAD

**Issue by cortado** [Danielhiversen/home_assistant_adax#40]
Would be great to have the integration calculate the power consumption. In the Adax app you can set the heaters effect (W). That could also be set in the intehgration, and then it could deliver the calculated consumption. Also would be great to have heating true/false as a variable to be able to monitor when a device is on.

Something that could be added?

**Comment by Danielhiversen** [comment]
Not exposed in the adax API today

**Comment by cortado** [comment]
> Not exposed in the adax API today

If you meant the consumption:
I know, but all we need is to put in a variable in config.yaml that is the heaters effect (100W), and then if you can detect if the heater is actually heating, you have the consumption :) 

If it is not possible to detect if it is actually heating, then i guess it is not doable.
