### ISSUE TITLE
Just temperature as an entity, not 'climate'

### ISSUE THREAD

**Issue by thefunkygibbon** [Danielhiversen/home_assistant_adax#41]
Is there a way to create a temperature entity for the heater as well as the 'climate' (ie so the object is simply the current temp, rather than current and set temps).

**Comment by thefunkygibbon** [comment]
![image](https://user-images.githubusercontent.com/19172392/129010255-76bef436-d209-4da4-8a44-9850fbbba21a.png)

just for reference.   'conservatory' is my adax heater.  which as you can see is different in its format than any of the other heaters / thermometers in the house

**Comment by Danielhiversen** [comment]
Use a template sensor https://www.home-assistant.io/integrations/template/
