### ISSUE TITLE
ADAX local api can't work?

### ISSUE THREAD

**Issue by zsgodor** [Danielhiversen/home_assistant_adax#48]
Hi Daniel,
Can you any information ADAX local api? (https://api-1.adax.no/client-api)
My home assistant system can't connect yesterday.
The error is bad gateway, i think the api doesn't work.
Logger: adax
Source: custom_components/adax/config_flow.py:25
Integration: Adax (documentation, issues)
First occurred: 06:05:31 (1 occurrences)
Last logged: 06:05:31

Adax: Failed to login to retrieve token: 502 Bad Gateway

Thank You for your reply.

**Comment by zsgodor** [comment]
Hey, Thank You for your fast reply, I send yesterday two notice by adax support, and today speak my local support.
If you have any information, i write here.
I have a question, if i want use adax local, must need an bluetooth device my HA server?
Because my server on the roof attic, too far my heater, the bluetooth connection doesn't work.

**Comment by SupraJames** [comment]
It would be interesting to hear from Daniel about this. I have the same issue. I can't use Local at the moment, because my HA instance is a VM located far away from the heater, and of course does not have Bluetooth!

It would be really good if there was a script / app which could be run on a local device (which has bluetooth) to perform the initial setup of the heater, where you pair and configure the WiFi credentials, and obtain the local API token. You then add the heater's IP address and Token to HA, and job done.

**Comment by Danielhiversen** [comment]
It works fine here, so I do not know

**Comment by zsgodor** [comment]
Hey Daniel,
I'm very happy if your integration is work, but my integration isn't work, now.
Can you help me what can i do? Reinstall the integration or what?
Logger: adax
Source: /usr/local/lib/python3.10/site-packages/adax/__init__.py:192
First occurred: 2022. november 1. 22:29:07 (3 occurrences)
Last logged: 09:43:52
![Képernyőfotó 2022-11-02 - 9 44 09](https://user-images.githubusercontent.com/64435192/199442017-ddb01f8d-3365-4041-a9fd-727c7888cc40.png)
Timed out when connecting to Adax for token

**Comment by SupraJames** [comment]
That's a bit odd. Even connecting to the API endpoint from a completely unrelated VPS on the internet (completely different IP from my house) results in a time out:

```
[jamesp@frankie2 ~]$ wget https://api-1.adax.no/client-api
--2022-11-02 04:44:44--  https://api-1.adax.no/client-api
Resolving api-1.adax.no (api-1.adax.no)... 51.120.98.192
Connecting to api-1.adax.no (api-1.adax.no)|51.120.98.192|:443... connected.
HTTP request sent, awaiting response...
```

You definitely getting a good connection and token from api-1.adax.no Daniel?

**Comment by zsgodor** [comment]
I'm sure the fault is the adax api site, now i connected successfully, but my entity is missing, and the connection "timed out"
I'm very unhappy, this time the heating season, i don't know what is the problem Adax api, i will fix it as soon as possible.


![Képernyőfotó 2022-11-02 - 10 01 27](https://user-images.githubusercontent.com/64435192/199448600-3620cd35-5300-4451-9240-162f89c388e9.png)

Logger: adax
Source: /usr/local/lib/python3.10/site-packages/adax/__init__.py:192
First occurred: 10:01:23 (1 occurrences)
Last logged: 10:01:23

Timed out when connecting to Adax for token

**Comment by SupraJames** [comment]
I'm getting a response now indicating the API server is 'stopped'

```
<body bgcolor="#00abec">
	<div id="feature">
		<div id="content">
			<h1 id="unavailable">Error 403 - This web app is stopped.</h1>
			<p id="tryAgain">The web app you have attempted to reach is currently stopped and does not accept any
				requests. Please try to reload the page or visit it again soon.</p>
			<p id="toAdmin">If you are the web app administrator, please find the common 403 error scenarios and
				resolution <a href="https://go.microsoft.com/fwlink/?linkid=2095007" target="_blank">here</a>. For
				further troubleshooting tools and recommendations, please visit <a
					href="https://portal.azure.com/">Azure Portal</a>.</p>
		</div>
	</div>
</body>
```

So, this is 100% not the fault of the integration. 

This is definitely prompting me to switch to pure local control as I don't want to rely on this service. I have been looking through the code but I am quickly seeing that modifying the integration is far beyond my ability, so I would humbly ask @Danielhiversen to consider a feature request:

Please allow a configuration option in the UI to skip the bluetooth heater registration part, and prompt for heater IP and secret Token instead. Perhaps a 'My heater is already configured' option or similar.

Then, I can use your https://github.com/Danielhiversen/pyAdaxLocal python module to configure the heater using my laptop and then just give the details to the HA integration.

**Comment by zsgodor** [comment]
I talk about my local dealer, He ask the adax nl, what is the problem the api.
If i have any information, write here.

**Comment by SupraJames** [comment]
@zsgodor it seems OK for me now too, maybe try again?

**Comment by zsgodor** [comment]
I delete the integration and re add, it seems OK for me now.
Huhh i will wait local api without bluetooth.
