### ISSUE TITLE
ADAX Heaters very slow to update via cloud

### ISSUE THREAD

**Issue by caribo** [Danielhiversen/home_assistant_adax#51]
Hey @Danielhiversen 

When I set the temperature in HA and it is the replicated in the Adax app within seconds, but  the heaters themselves are not updated. It takes 5-10 minutes for the heaters to respond.

In comparison, if I change the temperature in the app, the heaters update immediately; but ONLY if my phone/app is connected to the local network. Changing the temperature in the adax app when not connected to my wifi results in the long wait again. I guess this is because the heaters are polling for updates? and the app cannot reach them directly unless connected to wifi?

So the question is... can the addon work with adax in the the cloud and **also** send temperature updates directly to the heaters locally? as this is seemingly what the adax app does?

The 5-10 minute lag in changing the temperature is a nuisance.

**Comment by Danielhiversen** [comment]
For local access you should use: https://github.com/Danielhiversen/pyAdaxLocal

**Comment by caribo** [comment]
won't this stop the adax app working though? it's important that the app works for me...

**Comment by Danielhiversen** [comment]
Yes, that will disconnect it from the Adax cloud.
